AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create EFS Storage

Resources:

  #-----------------------------------------------------------------------------
  # Creating VPC for EFS file system
  #-----------------------------------------------------------------------------

  MountTargetVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
  
  #-----------------------------------------------------------------------------
  # Creating Subnet for EFS file system
  #-----------------------------------------------------------------------------

  MountTargetSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.31.1.0/24
      VpcId: !Ref MountTargetVPC
      AvailabilityZone: "us-east-1a"
  
  #-----------------------------------------------------------------------------
  # Creating EFS file system
  #-----------------------------------------------------------------------------

  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      AvailabilityZoneName: us-east-1a
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      FileSystemTags:
        - Key: Name
          Value: TestFileSystem
      # FileSystemPolicy:
      #   Version: "2012-10-17"
      #   Statement:
      #     - Effect: "Allow"
      #       Action:
      #         - "elasticfilesystem:ClientMount"
      #       Principal:
      #           AWS: 'arn:aws:iam::736752541976:role/AmazonElasticFileSystemFullAccess-role'
      KmsKeyId: !GetAtt 
        - key
        - Arn
  
  #-----------------------------------------------------------------------------
  # Creating the KMS Key
  #-----------------------------------------------------------------------------

  key:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action:
              - 'kms:*'
            Resource: 
              - '*'
  #-----------------------------------------------------------------------------
  # reating the Mount Target
  #-----------------------------------------------------------------------------

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Ref MountTargetSubnetOne
      SecurityGroups:
      - !GetAtt MountTargetVPC.DefaultSecurityGroup
  
  #-----------------------------------------------------------------------------
  # Creating AWS EFS Access Point
  #-----------------------------------------------------------------------------

  AccessPointResource:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: !Ref FileSystemResource
      PosixUser:
        Uid: "13234"
        Gid: "1322"
        SecondaryGids:
          - "1344"
          - "1452"
      RootDirectory:
        CreationInfo:
          OwnerGid: "708798"
          OwnerUid: "7987987"
          Permissions: "0777"
        Path: "/testcfn/abc"
