apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rapid7-monitor
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - nodes
  - pods
  - services
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - rapid7-cluster-id
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rapid7-monitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rapid7-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rapid7-monitor
subjects:
- kind: ServiceAccount
  name: rapid7-monitor
  namespace: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: rapid7
  labels:
    name: rapid7
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rapid7-monitor
  name: rapid7-monitor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rapid7-monitor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: rapid7-monitor
    spec:
      containers:
      - image: rapid7/kubernetes-monitor:latest
        imagePullPolicy: IfNotPresent
        name: kubernetes-agent
        env:
        - name: CLUSTER_NAME
          value: my_cluster_name
        - name: RAPID7_MONITOR_KEY
          valueFrom:
            secretKeyRef:
              name: rapid7-monitor
              key: monitor-key
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
      restartPolicy: Always
      serviceAccountName: rapid7-monitor

# Installation Instructions
# Run this in your Kubernetes terminal:
# kubectl create secret generic rapid7-monitor --from-literal=monitor-key="us:78c224ed-89da-43f0-88f4-9f95b42d7527" --namespace="default"

# Then apply the config file (attached to this email) by running this command:
# kubectl apply -f kubernetes-monitor.yml

# Kubernetes Monitor
# The Rapid7 Kubernetes Monitor is intended to be deployed to Kubernetes clusters and configured to identify instantiated containers. Note that users will need to deploy only one monitor per cluster.

# https://hub.docker.com/r/rapid7/kubernetes-monitor

# Deploying the Rapid7 Kubernetes Monitor
# Integrating your Kubernetes environment with InsightVM can be accomplished by pulling the Rapid7 Kubernetes Monitor from DockerHub, deploy this to each cluster, and performing a few configuration steps. Once configured, data will appear in the Container Security section of InsightVM.

# Viewing Kubernetes data
# After the monitor is deployed and configured, users will see Kubernetes data in the following areas of the Container Security section of InsightVM: